# Generated by Django 3.1.3 on 2020-11-22 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Rate',
            new_name='ProductRate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='productfile',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='product.product'),
        ),
    ]
